apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.66.144
  type: LoadBalancer
